[Feat] addUpdateCourse
Runnect/Runnect-Server pull request #155
Opened 2023-04-09 11:21 UTC by funnysunny08

#149

### 😶 무슨 이슈인가요?

---
#149 

### 🤔 어떻게 이슈를 해결했나요?

---
*for문 통해서 수화님이 짜주신 원시쿼리로 할까 하다가 findMany로 courseIdList만들고 다시 updateMany 하는 걸로 했눈데.. 뭐가 나을까욤...?*
- publicCourseIdList를 사용하여 course findMany 하여서 courseIdList 만듦
- 퍼블릭 코스 삭제 한 후
- courseIdList를 토대로 updateMany

### 🤯 주의할 점이 있나요?

---

2023-04-09 17:17 UTC, YuSuhwa-ve requested changes

2023-04-09 17:17 UTC, YuSuhwa-ve commented on src/service/publicCourseService.ts
> +
좋아요~
나중에 prisma transaction을 사용해서 묶어주면 되니깐!
역시 orm이 보기에 더 깔끔하군아 bbb

2023-04-09 17:17 UTC, YuSuhwa-ve commented on src/service/publicCourseService.ts
> +
아래 이미지는 현 pr에는없지만, 현 dev에는 있는 `deletePublicCourse`의 에러로직입니다
<img width="605" alt="image" src="https://user-images.githubusercontent.com/65851554/230786706-5fdf5914-a42f-4442-86c1-42afc8eeee28.png">
이 에러로직은 각 prisma 함수의 결과물로 count만 나타나서 인자로 들어온 `publicCourseId` 중  어느 아이디가 유효한지 유효하지 않은지 파악할 수 없어서 저렇게만 간단하게 처리했는데, 
`getCourseId`를 통해 들어온 `publicCourseIdList` 중 어떤 아이디가 존재하는 아이디인지 파악할수 있으니까 좀 더 자세하게  에러 처리가 가능할 것 같아요!

예를 들어 `getCourseId`의 select 단에 id(publicCourseId)를 추가해서, 들어오는 `publicCourseIdList'` 와 비교해 하나라도 존재하는 아이디가 아닌경우 이후 삭제로직을 실행하지 않고 바로 에러를 반환하도록 하면서, `publicCourseIdList'중 정확히 어떤 id가 유효하지않은지 responsemessage로 보내준다던지 에러로직을 수정할 수 있을듯

2023-04-10 01:07 UTC, RinRinPARK commented on src/service/publicCourseService.ts
> +
제가 보기에도 원시쿼리보다 이 방법이 깔끔해보입니다!! 고생했어용~~~

2023-04-21 14:23 UTC, merged